version: '3.8'

services:
  app:
    build: .
    container_name: fast_zero_app
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql+psycopg://user:pass@db:5432/fast_zero_db"
      SECRET_KEY: "secret"
      ALGORITHM: "HS256"
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    volumes:
      - .:/app

  db:
    image: postgres:latest
    container_name: fast_zero_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: fast_zero_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
